---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/mhassanja/public_html/bouncydigital.com
    - /bin/cp -R .next/. $DEPLOYPATH/.next/
    - /bin/cp -R public/. $DEPLOYPATH/public/
    - /bin/cp server.js $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp next.config.ts $DEPLOYPATH/
    - /bin/cp next-sitemap.config.js $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt

